
POST http://localhost:8080/books/
content-type: application/json

{
  "title": "Lorem ipsum",
  "description": "Dolor sit amet, consectetur adipiscing elit",
  "authors": ["Admin", "User"]
}

###

GET http://localhost:8080/books
###

PATCH  http://localhost:8080/books/5f391b1ab7e18b0082d7da26
content-type: application/json

{
  "title": "New title"
}
###

DELETE http://localhost:8080/books/5f391b5391b53f009045f5dd