
export const GET_BOOKS_USER_REQUEST = 'GET_BOOKS_USER_REQUEST';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';
export const GET_BOOKS_ASYNC = 'GET_BOOKS_ASYNC';
export const GET_BOOKS_LOADING = 'GET_BOOKS_LOADING';

export const SHOW_BOOKS = 'SHOW_BOOKS_USER_REQUEST';
export const SHOW_BOOKS_ERROR = 'SHOW_BOOKS_ERROR';
export const SHOW_BOOKS_ASYNC_ = 'SHOW_BOOKS_ASYNC';