
export const GET_BOOKS_USER_REQUEST = 'GET_BOOKS_USER_REQUEST';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';
export const GET_BOOKS_ASYNC = 'GET_BOOKS_ASYNC';

export const SHOW_BOOKS_USER_REQUEST = 'SHOW_BOOKS_USER_REQUEST';
export const SHOW_BOOKS_ERROR = 'SHOW_BOOKS_ERROR';
export const SHOW_BOOKS_ASYNC = 'SHOW_BOOKS_ASYNC';

export const SAVE_BOOK_USER_REQUEST = 'SAVE_BOOK_USER_REQUEST';
export const SAVE_BOOK_ERROR = 'SAVE_BOOK_ERROR'
export const SAVE_BOOK_ASYNC = 'SAVE_BOOK_ASYNC';

export const DELETE_BOOK_USER_REQUEST = 'DELETE_BOOK_USER_REQUEST';
export const DELETE_BOOK_ERROR = 'DELETE_BOOK_ERROR';
export const DELETE_BOOK_ASYNC = 'DELETE_BOOK_ASYNC';
